// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ghderddsrhslhuhubdcq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdoZGVyZGRzcmhzbGh1aHViZGNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NTE5MTgsImV4cCI6MjA3NDEyNzkxOH0.SVwcsTm6sT2F-ss2mV76w6PukL5JiIUc6dYvoD0bNDs";

// Import the supabase client like this:
// import { supabase } from "../integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
